#    BobTheBot Live version
##   Created by SamVolvo
###  Website: https://samvolvo.com/BobTheBot


token: ""

# DataBase
db-user: "samvolvo"
db-psw: "yolo"
db-url: "jdbc:mysql://localhost:3306/testbase"
